exclude: '.*\.(resx|Designer.cs|xti|tcscopex|tsproj)'
repos:
  - repo: https://github.com/pcdshub/pre-commit-hooks.git
    rev: v1.4.0
    hooks:
      - id: twincat-leading-tabs-remover
      - id: twincat-lineids-remover
      - id: twincat-xml-format
      - id: check-fixed-library-versions
      - id: no-product-version
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      # Removes trailing white spaces
      - id: trailing-whitespace
      # Checks yaml files for parseable syntax
      - id: check-yaml
      # Prevents git from committing large files
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: '\.(TcPOU|TcDUT|TcTTO|TcGVL|TcGTLO|TcVMO|TcVis|plcproj|tsproj|xti)$'
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: stweep
        name: Format TwinCAT files with STweep
        entry: python stweep_format.py
        language: python
        # All files need to be passed at once, or else the license activation/deactivation fails
        require_serial: true
        files: '.*\.(TcPOU|TcDUT|TcTTO|TcGVL)'
  - repo: local
    hooks:
      - id: CSharpier
        name: Format C# files
        entry: dotnet csharpier
        language: system
        files: '.*\.(cs$)'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        # --select I sorts imports 
        args: [ --fix, --select, I  ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://gitlab.com/rruiter87/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: check-poetry
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude_types: ["markdown", "svg"]
        additional_dependencies:
          - prettier@2.6.2
          - "@prettier/plugin-xml@0.12.0"
